# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operatorUi.ui'
#
# Created: Wed May 15 13:01:40 2019
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(504, 514)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.main_pro_addr = QtGui.QLineEdit(self.groupBox)
        self.main_pro_addr.setObjectName(_fromUtf8("main_pro_addr"))
        self.gridLayout_3.addWidget(self.main_pro_addr, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.BCI2000_addr = QtGui.QLineEdit(self.groupBox)
        self.BCI2000_addr.setObjectName(_fromUtf8("BCI2000_addr"))
        self.gridLayout_3.addWidget(self.BCI2000_addr, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.wheechair_addr = QtGui.QLineEdit(self.groupBox)
        self.wheechair_addr.setObjectName(_fromUtf8("wheechair_addr"))
        self.gridLayout_3.addWidget(self.wheechair_addr, 1, 1, 1, 1)
        self.save_param = QtGui.QPushButton(self.groupBox)
        self.save_param.setObjectName(_fromUtf8("save_param"))
        self.gridLayout_3.addWidget(self.save_param, 1, 2, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.bt_task1 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task1.setObjectName(_fromUtf8("bt_task1"))
        self.gridLayout.addWidget(self.bt_task1, 2, 1, 1, 2)
        self.bt_task3 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task3.setObjectName(_fromUtf8("bt_task3"))
        self.gridLayout.addWidget(self.bt_task3, 3, 1, 1, 2)
        self.bt_task0 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task0.setObjectName(_fromUtf8("bt_task0"))
        self.gridLayout.addWidget(self.bt_task0, 2, 0, 1, 1)
        self.bt_task2 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task2.setObjectName(_fromUtf8("bt_task2"))
        self.gridLayout.addWidget(self.bt_task2, 3, 0, 1, 1)
        self.bt_auto_model = QtGui.QPushButton(self.groupBox_2)
        self.bt_auto_model.setObjectName(_fromUtf8("bt_auto_model"))
        self.gridLayout.addWidget(self.bt_auto_model, 0, 0, 1, 1)
        self.bt_cmd_model = QtGui.QPushButton(self.groupBox_2)
        self.bt_cmd_model.setObjectName(_fromUtf8("bt_cmd_model"))
        self.gridLayout.addWidget(self.bt_cmd_model, 0, 1, 1, 2)
        self.bt_task4 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task4.setObjectName(_fromUtf8("bt_task4"))
        self.gridLayout.addWidget(self.bt_task4, 4, 0, 1, 1)
        self.bt_task5 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task5.setObjectName(_fromUtf8("bt_task5"))
        self.gridLayout.addWidget(self.bt_task5, 4, 1, 1, 2)
        self.bt_new_trial = QtGui.QPushButton(self.groupBox_2)
        self.bt_new_trial.setObjectName(_fromUtf8("bt_new_trial"))
        self.gridLayout.addWidget(self.bt_new_trial, 1, 0, 1, 1)
        self.bt_cease_current_task = QtGui.QPushButton(self.groupBox_2)
        self.bt_cease_current_task.setObjectName(_fromUtf8("bt_cease_current_task"))
        self.gridLayout.addWidget(self.bt_cease_current_task, 1, 1, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.bt_tleft = QtGui.QPushButton(self.groupBox_3)
        self.bt_tleft.setObjectName(_fromUtf8("bt_tleft"))
        self.gridLayout_2.addWidget(self.bt_tleft, 1, 0, 1, 1)
        self.bt_rright = QtGui.QPushButton(self.groupBox_3)
        self.bt_rright.setObjectName(_fromUtf8("bt_rright"))
        self.gridLayout_2.addWidget(self.bt_rright, 2, 1, 1, 1)
        self.bt_reverse = QtGui.QPushButton(self.groupBox_3)
        self.bt_reverse.setObjectName(_fromUtf8("bt_reverse"))
        self.gridLayout_2.addWidget(self.bt_reverse, 0, 1, 1, 1)
        self.bt_rleft = QtGui.QPushButton(self.groupBox_3)
        self.bt_rleft.setObjectName(_fromUtf8("bt_rleft"))
        self.gridLayout_2.addWidget(self.bt_rleft, 2, 0, 1, 1)
        self.bt_forward = QtGui.QPushButton(self.groupBox_3)
        self.bt_forward.setObjectName(_fromUtf8("bt_forward"))
        self.gridLayout_2.addWidget(self.bt_forward, 0, 0, 1, 1)
        self.bt_tright = QtGui.QPushButton(self.groupBox_3)
        self.bt_tright.setObjectName(_fromUtf8("bt_tright"))
        self.gridLayout_2.addWidget(self.bt_tright, 1, 1, 1, 1)
        self.bt_stop = QtGui.QPushButton(self.groupBox_3)
        self.bt_stop.setObjectName(_fromUtf8("bt_stop"))
        self.gridLayout_2.addWidget(self.bt_stop, 3, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.groupBox.setTitle(_translate("Dialog", "设备信息", None))
        self.label.setText(_translate("Dialog", "主控", None))
        self.main_pro_addr.setText(_translate("Dialog", "127.0.0.1-9098", None))
        self.label_2.setText(_translate("Dialog", "BCI2000", None))
        self.BCI2000_addr.setText(_translate("Dialog", "127.0.0.1-9099", None))
        self.label_3.setText(_translate("Dialog", "设备", None))
        self.wheechair_addr.setText(_translate("Dialog", "127.0.0.1-9097", None))
        self.save_param.setText(_translate("Dialog", "保存参数", None))
        self.groupBox_2.setTitle(_translate("Dialog", "任务分发", None))
        self.bt_task1.setText(_translate("Dialog", "任务1", None))
        self.bt_task3.setText(_translate("Dialog", "任务3", None))
        self.bt_task0.setText(_translate("Dialog", "任务0", None))
        self.bt_task2.setText(_translate("Dialog", "任务2", None))
        self.bt_auto_model.setText(_translate("Dialog", "自动模式", None))
        self.bt_cmd_model.setText(_translate("Dialog", "命令模式", None))
        self.bt_task4.setText(_translate("Dialog", "任务4", None))
        self.bt_task5.setText(_translate("Dialog", "任务5", None))
        self.bt_new_trial.setText(_translate("Dialog", "新一轮控制准备", None))
        self.bt_cease_current_task.setText(_translate("Dialog", "中断当前任务", None))
        self.groupBox_3.setTitle(_translate("Dialog", "人工干预", None))
        self.bt_tleft.setText(_translate("Dialog", "左移", None))
        self.bt_rright.setText(_translate("Dialog", "右转", None))
        self.bt_reverse.setText(_translate("Dialog", "后退", None))
        self.bt_rleft.setText(_translate("Dialog", "左转", None))
        self.bt_forward.setText(_translate("Dialog", "前进", None))
        self.bt_tright.setText(_translate("Dialog", "右移", None))
        self.bt_stop.setText(_translate("Dialog", "停止", None))

