# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'operatorUi.ui'
#
# Created: Wed May 15 09:20:59 2019
#      by: PyQt4 UI code generator 4.7.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(395, 455)
        self.horizontalLayout = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox = QtGui.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.main_pro_addr = QtGui.QLineEdit(self.groupBox)
        self.main_pro_addr.setObjectName("main_pro_addr")
        self.gridLayout_3.addWidget(self.main_pro_addr, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 2, 1, 1)
        self.BCI2000_addr = QtGui.QLineEdit(self.groupBox)
        self.BCI2000_addr.setObjectName("BCI2000_addr")
        self.gridLayout_3.addWidget(self.BCI2000_addr, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.wheechair_addr = QtGui.QLineEdit(self.groupBox)
        self.wheechair_addr.setObjectName("wheechair_addr")
        self.gridLayout_3.addWidget(self.wheechair_addr, 1, 1, 1, 1)
        self.save_param = QtGui.QPushButton(self.groupBox)
        self.save_param.setObjectName("save_param")
        self.gridLayout_3.addWidget(self.save_param, 1, 2, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_auto_model = QtGui.QPushButton(self.groupBox_2)
        self.bt_auto_model.setObjectName("bt_auto_model")
        self.gridLayout.addWidget(self.bt_auto_model, 0, 0, 1, 1)
        self.bt_cmd_model = QtGui.QPushButton(self.groupBox_2)
        self.bt_cmd_model.setObjectName("bt_cmd_model")
        self.gridLayout.addWidget(self.bt_cmd_model, 0, 1, 1, 1)
        self.bt_train_mode = QtGui.QPushButton(self.groupBox_2)
        self.bt_train_mode.setObjectName("bt_train_mode")
        self.gridLayout.addWidget(self.bt_train_mode, 1, 0, 1, 2)
        self.bt_new_trial = QtGui.QPushButton(self.groupBox_2)
        self.bt_new_trial.setObjectName("bt_new_trial")
        self.gridLayout.addWidget(self.bt_new_trial, 2, 0, 1, 1)
        self.bt_cease_current_task = QtGui.QPushButton(self.groupBox_2)
        self.bt_cease_current_task.setObjectName("bt_cease_current_task")
        self.gridLayout.addWidget(self.bt_cease_current_task, 2, 1, 1, 1)
        self.bt_task0 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task0.setObjectName("bt_task0")
        self.gridLayout.addWidget(self.bt_task0, 3, 0, 1, 1)
        self.bt_task1 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task1.setObjectName("bt_task1")
        self.gridLayout.addWidget(self.bt_task1, 3, 1, 1, 1)
        self.bt_task2 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task2.setObjectName("bt_task2")
        self.gridLayout.addWidget(self.bt_task2, 4, 0, 1, 1)
        self.bt_task3 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task3.setObjectName("bt_task3")
        self.gridLayout.addWidget(self.bt_task3, 4, 1, 1, 1)
        self.bt_task4 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task4.setObjectName("bt_task4")
        self.gridLayout.addWidget(self.bt_task4, 5, 0, 1, 1)
        self.bt_task5 = QtGui.QPushButton(self.groupBox_2)
        self.bt_task5.setObjectName("bt_task5")
        self.gridLayout.addWidget(self.bt_task5, 5, 1, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.bt_tleft = QtGui.QPushButton(self.groupBox_3)
        self.bt_tleft.setObjectName("bt_tleft")
        self.gridLayout_2.addWidget(self.bt_tleft, 1, 0, 1, 1)
        self.bt_rright = QtGui.QPushButton(self.groupBox_3)
        self.bt_rright.setObjectName("bt_rright")
        self.gridLayout_2.addWidget(self.bt_rright, 2, 1, 1, 1)
        self.bt_reverse = QtGui.QPushButton(self.groupBox_3)
        self.bt_reverse.setObjectName("bt_reverse")
        self.gridLayout_2.addWidget(self.bt_reverse, 0, 1, 1, 1)
        self.bt_rleft = QtGui.QPushButton(self.groupBox_3)
        self.bt_rleft.setObjectName("bt_rleft")
        self.gridLayout_2.addWidget(self.bt_rleft, 2, 0, 1, 1)
        self.bt_forward = QtGui.QPushButton(self.groupBox_3)
        self.bt_forward.setObjectName("bt_forward")
        self.gridLayout_2.addWidget(self.bt_forward, 0, 0, 1, 1)
        self.bt_tright = QtGui.QPushButton(self.groupBox_3)
        self.bt_tright.setObjectName("bt_tright")
        self.gridLayout_2.addWidget(self.bt_tright, 1, 1, 1, 1)
        self.bt_stop = QtGui.QPushButton(self.groupBox_3)
        self.bt_stop.setObjectName("bt_stop")
        self.gridLayout_2.addWidget(self.bt_stop, 3, 0, 1, 2)
        self.gridLayout_4.addWidget(self.groupBox_3, 2, 0, 1, 1)
        self.horizontalLayout.addLayout(self.gridLayout_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("Dialog", "设备信息", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "主控", None, QtGui.QApplication.UnicodeUTF8))
        self.main_pro_addr.setText(QtGui.QApplication.translate("Dialog", "127.0.0.1-9098", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "BCI2000", None, QtGui.QApplication.UnicodeUTF8))
        self.BCI2000_addr.setText(QtGui.QApplication.translate("Dialog", "127.0.0.1-9099", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "设备", None, QtGui.QApplication.UnicodeUTF8))
        self.wheechair_addr.setText(QtGui.QApplication.translate("Dialog", "127.0.0.1-9097", None, QtGui.QApplication.UnicodeUTF8))
        self.save_param.setText(QtGui.QApplication.translate("Dialog", "保存参数", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("Dialog", "任务分发", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_auto_model.setText(QtGui.QApplication.translate("Dialog", "自动模式", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_cmd_model.setText(QtGui.QApplication.translate("Dialog", "命令模式", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_train_mode.setText(QtGui.QApplication.translate("Dialog", "训练模式", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_new_trial.setText(QtGui.QApplication.translate("Dialog", "新一轮控制准备", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_cease_current_task.setText(QtGui.QApplication.translate("Dialog", "中断当前任务", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_task0.setText(QtGui.QApplication.translate("Dialog", "任务0", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_task1.setText(QtGui.QApplication.translate("Dialog", "任务1", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_task2.setText(QtGui.QApplication.translate("Dialog", "任务2", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_task3.setText(QtGui.QApplication.translate("Dialog", "任务3", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_task4.setText(QtGui.QApplication.translate("Dialog", "任务4", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_task5.setText(QtGui.QApplication.translate("Dialog", "任务5", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("Dialog", "人工干预", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_tleft.setText(QtGui.QApplication.translate("Dialog", "左移", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_rright.setText(QtGui.QApplication.translate("Dialog", "右转", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_reverse.setText(QtGui.QApplication.translate("Dialog", "后退", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_rleft.setText(QtGui.QApplication.translate("Dialog", "左转", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_forward.setText(QtGui.QApplication.translate("Dialog", "前进", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_tright.setText(QtGui.QApplication.translate("Dialog", "右移", None, QtGui.QApplication.UnicodeUTF8))
        self.bt_stop.setText(QtGui.QApplication.translate("Dialog", "停止", None, QtGui.QApplication.UnicodeUTF8))

